repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-ast # Simply check whether files parse as valid python
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
      - id: ruff-format
  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
    # Check for secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks

    # Run pytest
  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: [pytest]
        stages: [commit]
