services:
  pmp-summary:
    image: rickjhoppe/pmp-summary:latest
    container_name: pmp-summary
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - WASTEBIN_URL=${WASTEBIN_URL}
      - NTFY_URL=${NTFY_URL}
